//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppGroupByAndFilterByGridView
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyRelation
    {
        public int EmployeeId { get; set; }
        public string RelationType { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public Nullable<byte> Age { get; set; }
        public string CareerTitle { get; set; }
        public string UrgentContact { get; set; }
    }
}
